version: 1

project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: dist/community.lazycat.app.its-mytabs.lpk
  target_arch: amd64

update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: its-mytabs

build:
  run_buildscript: false

images:
  - id: its-mytabs
    target: service
    service: its-mytabs
    source: louislam/its-mytabs
    channel: stable
    sort: semver
    tag_regex: '^\d+\.\d+\.\d+$'
    delivery:
      mode: mirror
      image_template: docker.1ms.run/louislam/its-mytabs:{tag}
      require_digest_match: true

stores:
  official:
    enabled: false
  private:
    enabled: true
    skip_if_version_exists: true
    name: It's MyTabs
    summary: Published from CI
