name: It's MyTabs
package: community.lazycat.app.its-mytabs
version: 1.0.0
min_os_version: 1.3.8
description: 开源，基于网页，可自托管的吉他/贝斯乐谱查看器和播放器，类似于 Songsterr。
homepage: https://github.com/louislam/its-mytabs/
author: louislam
application:
  subdomain: its-mytabs
  background_task: true
  public_path:
    - /

  upstreams:
    - location: /
      backend: http://its-mytabs:47777/

services:
  its-mytabs:
    container_name: its-mytabs
    #  louislam/its-mytabs:1.0.0
    image: registry.lazycat.cloud/czyt/louislam/its-mytabs:69e52b1692c79740
    binds:
      - /lzcapp/var/data:/app/data

locales:
  zh:
    name: "It's MyTabs"
    description: "开源，基于网页，可自托管的吉他/贝斯乐谱查看器和播放器，类似于 Songsterr。"
  en:
    name: "It's MyTabs"
    description: "Open source, web based, self hostable guitar/bass tab viewer and player, similar to Songsterr."
