application:
  subdomain: its-mytabs
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://its-mytabs:47777/
services:
  its-mytabs:
    # louislam/its-mytabs:1.0.0
    # upstream: louislam/its-mytabs:1.7.0
    image: docker.1ms.run/louislam/its-mytabs:1.7.0
    binds:
      - /lzcapp/var/data:/app/data
